### PR TITLE
include AddChannel() transform

### PR DESCRIPTION
**Pull request by Dale-Black**

### CODE REVIEW

**Comment by lorenzoh** [comment]
What is the use case for `AddChannel()`? Is it to turn an n-dimensional `Image` into a n+1-dimensional `Array` item with the color channels expanded as `ImageToTensor` currently does for RGB images? The motivation isn't clear, it would be great to have more background in an issue or PR.

The current implementation also isn't very general as it currently duplicates code for different item types. Since these actually have the same supertype `AbstractArrayItem`, that can be used to dispatch. Additionally, to make it easier to implement these kinds of transformations (applying a function to the data inside an item), the pattern could be written like this:

```julia
struct MapItemData <: Transform
    f
end

apply(tfm::MapItemData, item::AbstractItem; randstate = nothing) = setitemdata(item, tfm.f(itemdata(item)))
```

Which makes defining `AddChannel()` simple:

```julia
AddChannel() = MapItemData(a -> reshape(a, size(a)..., 1))
```

**Comment by Dale-Black** [comment]
Oh okay I guess I didn't quite understand `ImageToTensor()`. If you have a 3D grayscale image `img = Array{Float32, 3}` that you pass through an Image Item `Image(Gray.(img))`and then call `ImageToTensor()`, it does not produce an array of `size = (x, y, z, 1)` but instead remains `size = (x, y, z)`. That is the motivation behind the `AddChannel()` transform but your `MapItemData` is much more general and should work.

I am confused on how to implement the `setitemdata` portion of this transform though if you could expand on that

**Comment by lorenzoh** [comment]
Ah, it's `setdata` that is already implemented in DataAugmentation.jl (I changed the name at some point and got it confused).

One performance nitpick: instead of calling `Gray.(img)` you'll usually want to call `colorview(Gray, img)` which doesn't need to copy the whole array.

**Comment by Dale-Black** [comment]
That all worked and thanks for the `MapItemData()` example because it was a little "aha" moment for me in understanding some of the power behind Julia's type system

**Comment by lorenzoh** [comment]
No problem! Did you close this because the solution was so small? I think `MapItemData` should be added to the library with some documentation and examples like `AddChannel` but of course you don't have to do that, but let me know if you want me to reopen this 👍

**Comment by Dale-Black** [comment]
Oh I would love to implement that. I'll update it when it's ready!

**Comment by lorenzoh** [comment]
Thanks!

**Pull request closed without merging**
