### PR TITLE
Add 3d rotations

### PR DESCRIPTION
**Pull request by paulnovo**
This adds 3D support to the Rotate transformation, and introduces
RotateX, RotateY, and RotateZ for 3D rotations around the x, y, and z
axes.

### PR Checklist

- [x] Tests are added
- [x] Documentation, if applicable

### CODE REVIEW

**Comment by CarloLucibello** [comment]
Thanks! Could you add to the documentation in `doc/src/transforms.md` and `docs/src/ref.md`?

**Comment by paulnovo** [comment]
> Thanks! Could you add to the documentation in `doc/src/transforms.md` and `docs/src/ref.md`?

Hi @CarloLucibello, thanks for taking a look. I just pushed two commits. The first  [commit](https://github.com/FluxML/DataAugmentation.jl/pull/93/commits/112fb66c63735615a7041cd1892ccb22e149e210) is probably what you were looking for, just adding the documentation to ref.md. In a [second commit](https://github.com/FluxML/DataAugmentation.jl/pull/93/commits/301319bee6c77d75605dbf1ca0e7d8a1296db71d),  I went much further with a bit of reorganization, but maybe not what you wanted. I can pull this commit out into a separate PR if that makes more sense.

**Comment by CarloLucibello** [comment]
I like the reorganization! still something to do or we can merge?

**Review by CarloLucibello — APPROVED** [review]

**Comment by paulnovo** [comment]
@CarloLucibello I am all done with this, you can merge.

**Pull request merged**
